#!/usr/bin/env bash
# Transfers a file from our client to a server
#
if [ $# -lt 4 ]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  echo "Transferring file..."
  scp -v -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
  if [ $? -eq 0 ]; then
    echo "File transfer successful."
  else
    echo "File transfer failed."
  fi
fi
